language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install coverage
  - pip install codecov
install:
  - pip install .
  # Set minimum requirements
  - pip install matplotlib==3.3.3
  - pip install networkx==2.5
  - pip install pandas==1.1.3
  - pip install SALib==1.3.7
  - pip install IPython==7.15.0
  - pip install ipywidgets==7.5.1
script:
  - coverage run -m pytest  # run tests and assess coverage
after_success:
  - codecov  # submit coverage